#! /bin/bash
echo "
On thursday and friday Damian and I worked on gathering parts for and working on our safe. We were able to wrap up with the wiring on friday.
On monday, Damian and I will work on printing our 3D box. We're most likely going to continue to work on the box until maybe wednesday?
On thursday, we plan on putting the electronic parts of the safe into the chassis, including the 9V battery, and installing the servo (our locking mechanism.)
On friday, we expect to continue what we did on thursday, if we didn't finish."
